### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ihomecall** [venj/Swift-Photos#1]
I compiled the code and ran it and it cannot load photos
stops with exception at here

func localDirectoryForPost(link:String, create:Bool = true) -> String? {
    let host = NSURL(string: link)!.host!

2016-01-01 15:36:10.826 Swift Photos[63342:25974194]  INFO: Reveal Server started (Protocol Version 18).
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb)

**Comment by venj** [comment]
I didn't include the original urls in Common.swift. Since these addresses are kind of secretive. Sorry.
